name: Docker Build
on:
  push:
    branches:
      - nya

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate .env file
        run: 'echo "$DOT_ENV" > .env'
        shell: bash
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Send success webhook
        run: curl ${{ secrets.DOCKER_BUILD_SUCCESS_WEBHOOK }}?subject=elk
